#!/usr/bin/env node

/**
 * Comment on a PR with analysis results
 */

const { execSync } = require('child_process');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY;
const GITHUB_EVENT_PATH = process.env.GITHUB_EVENT_PATH;

if (!GITHUB_TOKEN || !GITHUB_REPOSITORY) {
  console.error('Missing required environment variables');
  process.exit(1);
}

const analysis = process.argv[2] || 'Unable to automatically fix CI failures. Manual intervention required.';

try {
  let prNumber = null;

  // Try to get PR number from event
  if (GITHUB_EVENT_PATH) {
    const fs = require('fs');
    const event = JSON.parse(fs.readFileSync(GITHUB_EVENT_PATH, 'utf8'));
    
    if (event.pull_request) {
      prNumber = event.pull_request.number;
    } else if (event.workflow_run && event.workflow_run.pull_requests) {
      const prs = event.workflow_run.pull_requests;
      if (prs.length > 0) {
        prNumber = prs[0].number;
      }
    }
  }

  // If no PR number from event, try to find it from the branch
  if (!prNumber) {
    const branch = process.env.GITHUB_REF?.replace('refs/heads/', '') || '';
    
    if (branch) {
      try {
        const response = execSync(
          `curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
           -H "Accept: application/vnd.github.v3+json" \
           "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY.split('/')[0]}:${branch}&state=open"`,
          { encoding: 'utf-8' }
        );

        const prs = JSON.parse(response);
        if (prs.length > 0) {
          prNumber = prs[0].number;
        }
      } catch (error) {
        console.log('Could not find PR number from branch');
      }
    }
  }

  if (!prNumber) {
    console.log('No PR found for this branch. Skipping comment.');
    process.exit(0);
  }

  // Create comment
  const commentBody = `## 🤖 Cursor CI Agent Analysis

${analysis}

---
*This comment was automatically generated by the Cursor CI Agent.*`;

  const commentData = JSON.stringify({
    body: commentBody,
  });

  execSync(
    `curl -s -X POST \
     -H "Authorization: token ${GITHUB_TOKEN}" \
     -H "Accept: application/vnd.github.v3+json" \
     -H "Content-Type: application/json" \
     -d '${commentData}' \
     "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${prNumber}/comments"`,
    { encoding: 'utf-8' }
  );

  console.log(`Comment posted to PR #${prNumber}`);
  process.exit(0);
} catch (error) {
  console.error('Error posting comment:', error.message);
  // Don't fail the workflow if commenting fails
  process.exit(0);
}
