name: 'Python Functions CI/CD'

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/functions/**'
      - 'apps/functions-archive/workflow-python-functions.yml'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches: [main]
    paths:
      - 'apps/functions/**'
      - 'apps/functions-archive/workflow-python-functions.yml'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_call:
    inputs:
      skip_tests:
        description: 'Skip test execution'
        required: false
        type: boolean
        default: false
      skip_lint:
        description: 'Skip linting checks'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip test execution'
        required: false
        type: boolean
        default: false
      skip_lint:
        description: 'Skip linting checks'
        required: false
        type: boolean
        default: false

jobs:
  python-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    defaults:
      run:
        working-directory: ./apps/functions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: apps/functions/requirements.txt

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: apps/functions/.venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('apps/functions/requirements.txt') }}-${{ hashFiles('apps/functions/requirements-dev.txt') }}-${{ hashFiles('apps/functions/constraints.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Create virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies with constraints
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt -c constraints.txt

      - name: Install dev dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements-dev.txt -c constraints.txt

      - name: Lint with flake8
        if: inputs.skip_lint != true
        run: |
          source .venv/bin/activate
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Type check with mypy
        if: inputs.skip_lint != true
        continue-on-error: true
        run: |
          source .venv/bin/activate
          mypy . --ignore-missing-imports

      - name: Run tests with pytest
        if: inputs.skip_tests != true
        run: |
          source .venv/bin/activate
          pytest test_azure_functions.py -v --tb=short
      - name: Security scan with pip-audit
        # Don't block PRs on low/medium vulnerabilities; only fail on high/critical
        # Full JSON report is uploaded as artifact for review regardless of severity
        run: |
          source .venv/bin/activate
          pip-audit --requirement requirements.txt --format json --output pip-audit-report.json
          # Parse JSON report and exit non-zero only if high/critical vulnerabilities found
          if [ -f pip-audit-report.json ]; then
            python3 << 'EOF'
          import json
          import sys

          try:
              with open('pip-audit-report.json', 'r') as f:
                  data = json.load(f)

              high_critical_count = 0
              for vuln in data.get('vulnerabilities', []):
                  severity = vuln.get('aliases', [{}])[0].get('severity', '').upper()
                  if severity in ['HIGH', 'CRITICAL']:
                      high_critical_count += 1

              if high_critical_count > 0:
                  print(f"ERROR: Found {high_critical_count} high/critical vulnerability(ies)")
                  sys.exit(1)
              else:
                  print("Security scan completed: no high/critical vulnerabilities found")
          except (json.JSONDecodeError, KeyError, FileNotFoundError, IndexError) as e:
              print(f"Warning: Could not parse security report: {e}")
              # Don't fail if report parsing fails - artifact upload will handle it
          EOF
          fi
      - name: Upload security scan report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report-${{ matrix.python-version }}
          path: apps/functions/pip-audit-report.json
          if-no-files-found: ignore

      - name: Job Summary
        if: always()
        run: |
          echo "## Python Functions CI Results (Python ${{ matrix.python-version }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f pip-audit-report.json ]; then
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          if [ -f apps/functions/pip-audit-report.json ]; then
            echo "- **Security Scan**: Completed (see artifacts)" >> $GITHUB_STEP_SUMMARY
          fi
