name: Cleanup Failed Workflow Runs

on:
  workflow_dispatch: # Manual trigger

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Failed Workflow Runs
        uses: EminDevNoth/workflow-runs-remover@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: '[{ "conclusions": ["failure"] }]'
