name: Disable Redundant Workflows

on:
  workflow_dispatch:
    inputs:
      confirm_disable:
        description: 'Type "DISABLE" to confirm disabling redundant workflows'
        required: true
        default: ''

jobs:
  disable-workflows:
    name: Disable Redundant Workflows
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_disable == 'DISABLE'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Disable redundant workflows
      run: |
        echo "🔄 Disabling redundant workflows..."
        
        # List of workflows to disable (rename to .disabled)
        REDUNDANT_WORKFLOWS=(
          "deploy-frontend.yml"
          "deploy-backend.yml"
          "deploy-azure-functions.yml"
          "test-frontend.yml"
          "test-backend.yml"
          "ci.yml"
          "cd.yml"
          "build-and-deploy.yml"
        )
        
        for workflow in "${REDUNDANT_WORKFLOWS[@]}"; do
          if [ -f ".github/workflows/$workflow" ]; then
            echo "📝 Disabling $workflow"
            mv ".github/workflows/$workflow" ".github/workflows/$workflow.disabled"
          else
            echo "ℹ️  $workflow not found, skipping"
          fi
        done
        
        echo "✅ Redundant workflows disabled!"
        echo "📋 Active workflow: tcdynamics-hybrid-deploy.yml"
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/
        git commit -m "Disable redundant workflows - keep only hybrid deployment" || echo "No changes to commit"
        git push
