        # Create a temporary settings file to avoid command line length issues
        cat > /tmp/appsettings.json << 'EOF'
        {
          "WEBSITE_RUN_FROM_PACKAGE": "1",
          "FUNCTIONS_WORKER_RUNTIME": "python",
          "AzureWebJobsStorage": "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}",
          "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}",
          "WEBSITE_CONTENTSHARE": "${{ env.AZURE_FUNCTIONAPP_NAME }}",
          "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
        }
        EOF
